name: build

on:
  push:
    branches:
      - main
      - hackathon

env:
  IMAGE_NAME: ghcr.io/rnishtala-sumo/kube-ebpf
  DOCKER_BUILDKIT: 1

jobs:
  kube-ebpf:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - run: docker build -t $IMAGE_NAME:latest .
      - run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:commit-${GITHUB_SHA:0:8}
      - run: docker push $IMAGE_NAME --all-tags